# Configuration related to self-hosted runner.
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - ubuntu-24.04-32core-graph-team-amd64
    - ubuntu-24.04-32core-graph-team-arm64
