$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":lint-roller: Lint"
    key: lint
    agents:
      queue: aspect-small-ubuntu-lts
    command: |
      ./tools/reformat.sh
      if ! git diff --quiet; then
        git diff
        echo ""
        echo "-----------------------------------"
        echo "Re-run ./tools/reformat.sh and push"
        echo "-----------------------------------"
        exit 1
      fi

      ./tools/lint.sh

  - key: aspect-workflows-upload
    label: ":aspect: Setup Aspect Workflows"
    commands: |
      rosetta steps | buildkite-agent pipeline upload
    agents:
      queue: aspect-small-ubuntu-lts
