$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      apt-get update -y && apt-get install -y gcc-10 gcc-10-base g++-10 libstdc++-10-dev
      update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
      echo "--- gcc"
      gcc -v
      echo "--- gcc"

      bazel build //...

      # Don't use //... as that will also try to update snapshots
      bazel test //test
