$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    env: 
      CI_BAZEL_REMOTE_CACHE: "https://storage.googleapis.com/sourcegraph_bazel_cache"
    key: build
    command: |
      # Keep this link in sync with Development.md
      wget -L https://github.com/bazelbuild/buildtools/releases/download/6.0.0/buildifier-linux-amd64 -O buildifier
      chmod +x buildifier
      mv buildifier /usr/local/bin/

      # Bazel handles the C++ toolchain
      bazel build @llvm_toolchain//:clang-format --remote_cache=$$CI_BAZEL_REMOTE_CACHE --google_credentials=/mnt/gcloud-service-account/gcloud-service-account.json

      # Lint the python code
      bazel build //tools:check --remote_cache=$$CI_BAZEL_REMOTE_CACHE --google_credentials=/mnt/gcloud-service-account/gcloud-service-account.json

      bazel build //... --config=ci --remote_cache=$$CI_BAZEL_REMOTE_CACHE --google_credentials=/mnt/gcloud-service-account/gcloud-service-account.json

      # Don't use //... as that will also try to update snapshots
      bazel test //test --test_output=errors --config=ci --remote_cache=$$CI_BAZEL_REMOTE_CACHE --google_credentials=/mnt/gcloud-service-account/gcloud-service-account.json
