$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
      add-apt-repository 'deb http://apt.llvm.org/focal/  llvm-toolchain-focal-15 main'
      apt-get install -y clang-15
      export CC=clang-15
      export CXX=clang++-15

      bazel build //...

      # Don't use //... as that will also try to update snapshots
      bazel test //test
