$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      ./tools/reformat.sh
      if ! git diff --quiet; then
        git diff
        echo ""
        echo "-----------------------------------"
        echo "Re-run ./tools/reformat.sh and push"
        echo "-----------------------------------"
        exit 1
      fi

      ./tools/lint.sh

      # Use RBE for builds (Ubuntu 22.04 container) since LLVM 21 requires glibc 2.34+
      # The --config=ci settings are included for test retries and other CI behaviors
      bazel --bazelrc=.bazelrc --bazelrc=.aspect/bazelrc/ci.bazelrc build //... --config=rbe

      # Don't use //... as that will also try to update snapshots
      bazel --bazelrc=.bazelrc --bazelrc=.aspect/bazelrc/ci.bazelrc test //test --config=rbe
