$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      # NOTE: Keep in sync with tools/vm_setup.sh
      curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
      add-apt-repository 'deb http://apt.llvm.org/focal/  llvm-toolchain-focal-15 main'
      # libstdc++-9 doesn't have <compare> from C++20
      apt-get install -y clang-15 libstdc++-10-dev
      export CC=clang-15
      export CXX=clang++-15

      # TODO(def: test-with-sanitizers) Using --config=dev
      # increases build time from 18min to 31min. Can we trim
      # some options to keep a fast build while having sanitizers?
      bazel build //...

      # Don't use //... as that will also try to update snapshots
      bazel test //test --test_output=errors
