$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      # Keep this link in sync with Development.md
      wget -L https://github.com/bazelbuild/buildtools/releases/download/6.0.0/buildifier-linux-amd64 -O buildifier
      chmod +x buildifier
      mv buildifier /usr/local/bin/

      # Bazel handles the C++ toolchain
      bazel build @llvm_toolchain//:clang-format

      ./tools/reformat.sh
      if ! git diff --quiet; then
        git diff
        echo ""
        echo "-----------------------------------"
        echo "Re-run ./tools/reformat.sh and push"
        echo "-----------------------------------"
        exit 1
      fi

      bazel build //... --config=ci

      # Don't use //... as that will also try to update snapshots
      bazel test //test --test_output=errors --config=ci
